services:
  psy-panel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ebraz-psy-panel
    ports:
      - "127.0.0.1:3002:3002"
    environment:
      BACKEND_API_URL: ${BACKEND_API_URL:-https://api.ebrazclinic.ir/}
      NODE_ENV: production
      PORT: 3002
      HOSTNAME: 0.0.0.0
    restart: unless-stopped
